services:
  homestead:
    build: .

    container_name: homestead

    ports:
      - "7312:7312"

    volumes:
      - ./media:/app/media
      - ./data:/app/data
      - ./config:/app/config

    restart: unless-stopped